name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        working-directory: ./deco-slack
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Run tests
        working-directory: ./deco-slack
        run: |
          poetry install
          poetry run pytest

      - name: Build and publish
        working-directory: ./deco-slack
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry build
          poetry publish
